import 'package:json_annotation/json_annotation.dart';
import 'package:crypto_trading_app/features/wallets/domain/entities/wallet_transaction.dart';
import 'package:crypto_trading_app/features/wallets/data/models/wallet_balance_model.dart';

part 'wallet_transaction_model.g.dart';

/// Data Transfer Object (DTO) for wallet transaction response from API
///
/// JSON structure from API:
/// ```json
/// {
///   "transactionId": "TXN_20260202_001",
///   "userId": 1,
///   "currencyId": 1,
///   "action": "CREDIT",
///   "amount": "5.5",
///   "refType": "DEPOSIT",
///   "refId": 12345,
///   "newBalance": {
///     "userId": 1,
///     "currencyId": 1,
///     "available": "55.5",
///     "frozen": "10.25",
///     "total": "65.75"
///   },
///   "timestamp": "2026-02-02T10:30:45.000Z"
/// }
/// ```
@JsonSerializable()
class WalletTransactionResponseModel {
  /// Unique transaction ID generated by backend
  @JsonKey(name: 'transactionId')
  final String transactionId;

  /// User ID performing the transaction (UUID v7)
  @JsonKey(name: 'userId')
  final String userId;

  /// Currency ID (UUID v7)
  @JsonKey(name: 'currencyId')
  final String currencyId;

  /// Action performed (CREDIT, DEBIT, FREEZE, UNFREEZE, TRANSFER)
  @JsonKey(name: 'action')
  final String action;

  /// Amount involved in transaction
  @JsonKey(name: 'amount')
  final String amount;

  /// Reference type (DEPOSIT, WITHDRAW, ORDER, TRADE, ADJUST, TRANSFER)
  @JsonKey(name: 'refType')
  final String refType;

  /// Reference ID (UUID v7)
  @JsonKey(name: 'refId')
  final String refId;

  /// New balance after transaction
  @JsonKey(name: 'newBalance')
  final WalletBalanceModel newBalance;

  /// Transaction timestamp (ISO 8601 format)
  @JsonKey(name: 'timestamp')
  final String timestamp;

  const WalletTransactionResponseModel({
    required this.transactionId,
    required this.userId,
    required this.currencyId,
    required this.action,
    required this.amount,
    required this.refType,
    required this.refId,
    required this.newBalance,
    required this.timestamp,
  });

  /// Create from JSON (used by json_serializable)
  factory WalletTransactionResponseModel.fromJson(Map<String, dynamic> json) =>
      _$WalletTransactionResponseModelFromJson(json);

  /// Convert to JSON (used by json_serializable)
  Map<String, dynamic> toJson() => _$WalletTransactionResponseModelToJson(this);

  /// Convert DTO to domain entity
  WalletTransactionResponse toDomain() {
    return WalletTransactionResponse(
      transactionId: transactionId,
      userId: userId,
      currencyId: currencyId,
      action: WalletTransactionAction.fromString(action) ??
          WalletTransactionAction.credit,
      amount: amount,
      refType: WalletReferenceType.fromString(refType) ??
          WalletReferenceType.deposit,
      refId: refId,
      newBalance: newBalance.toDomain(),
      timestamp: DateTime.parse(timestamp),
    );
  }

  @override
  String toString() {
    return 'WalletTransactionResponseModel(transactionId: $transactionId, action: $action, amount: $amount, timestamp: $timestamp)';
  }
}
