import 'package:equatable/equatable.dart';
import 'package:crypto_trading_app/domain/entities/wallet_balance.dart';

/// Wallet transaction action enum
///
/// Defines the type of action performed on wallet balance:
/// - CREDIT: Add money to available balance (deposit received)
/// - DEBIT: Remove money from available balance (withdrawal)
/// - FREEZE: Lock money from available to frozen (place order)
/// - UNFREEZE: Unlock money from frozen to available (cancel order)
/// - TRANSFER: Transfer money to another user
enum WalletTransactionAction {
  credit('CREDIT'),
  debit('DEBIT'),
  freeze('FREEZE'),
  unfreeze('UNFREEZE'),
  transfer('TRANSFER');

  final String value;

  const WalletTransactionAction(this.value);

  /// Convert string to enum value
  /// Returns null if string doesn't match any enum
  static WalletTransactionAction? fromString(String value) {
    for (final action in WalletTransactionAction.values) {
      if (action.value == value) return action;
    }
    return null;
  }
}

/// Wallet transaction reference type enum
///
/// Defines the reason/source for the transaction (audit trail):
/// - DEPOSIT: Money coming into wallet from external source
/// - WITHDRAW: Money leaving wallet to external address
/// - ORDER: Related to placing/canceling orders
/// - TRADE: Actual buy/sell transaction execution
/// - ADJUST: Manual adjustment by admin
/// - TRANSFER: Transfer between users
enum WalletReferenceType {
  deposit('DEPOSIT'),
  withdraw('WITHDRAW'),
  order('ORDER'),
  trade('TRADE'),
  adjust('ADJUST'),
  transfer('TRANSFER');

  final String value;

  const WalletReferenceType(this.value);

  /// Convert string to enum value
  /// Returns null if string doesn't match any enum
  static WalletReferenceType? fromString(String value) {
    for (final refType in WalletReferenceType.values) {
      if (refType.value == value) return refType;
    }
    return null;
  }
}

/// Request DTO for wallet transaction
class WalletTransactionRequest extends Equatable {
  /// Currency ID (1=BTC, 2=ETH, etc.)
  final int currencyId;

  /// Amount to transfer (decimal string, max 18 decimal places)
  /// Must match pattern: ^\d+(\.\d{1,18})?$
  final String amount;

  /// Action to perform (CREDIT, DEBIT, FREEZE, UNFREEZE, TRANSFER)
  final WalletTransactionAction action;

  /// Reference type (DEPOSIT, WITHDRAW, ORDER, TRADE, ADJUST, TRANSFER)
  final WalletReferenceType refType;

  /// Reference ID (deposit ID, order ID, withdrawal ID, etc.)
  final int refId;

  /// Target user ID (required only for TRANSFER action)
  final int? targetUserId;

  const WalletTransactionRequest({
    required this.currencyId,
    required this.amount,
    required this.action,
    required this.refType,
    required this.refId,
    this.targetUserId,
  });

  /// Convert to JSON for API request
  Map<String, dynamic> toJson() {
    return {
      'currencyId': currencyId,
      'amount': amount,
      'action': action.value,
      'refType': refType.value,
      'refId': refId,
      if (targetUserId != null) 'targetUserId': targetUserId,
    };
  }

  @override
  List<Object?> get props =>
      [currencyId, amount, action, refType, refId, targetUserId];
}

/// Response DTO for wallet transaction
class WalletTransactionResponse extends Equatable {
  /// Unique transaction ID generated by backend
  final String transactionId;

  /// User ID performing the transaction
  final int userId;

  /// Currency ID
  final int currencyId;

  /// Action performed
  final WalletTransactionAction action;

  /// Amount involved in transaction
  final String amount;

  /// Reference type
  final WalletReferenceType refType;

  /// Reference ID
  final int refId;

  /// New balance after transaction
  final WalletBalance newBalance;

  /// Transaction timestamp (ISO 8601 format)
  final DateTime timestamp;

  const WalletTransactionResponse({
    required this.transactionId,
    required this.userId,
    required this.currencyId,
    required this.action,
    required this.amount,
    required this.refType,
    required this.refId,
    required this.newBalance,
    required this.timestamp,
  });

  @override
  List<Object?> get props => [
        transactionId,
        userId,
        currencyId,
        action,
        amount,
        refType,
        refId,
        newBalance,
        timestamp,
      ];

  @override
  String toString() {
    return 'WalletTransactionResponse(transactionId: $transactionId, userId: $userId, currencyId: $currencyId, action: ${action.value}, amount: $amount, timestamp: $timestamp)';
  }
}
